server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30

log:
  path: "./app.log"
  level: 1

storage:
  host: "postgres"
  port: 5432
  db_name: "Questions"
  username: "myuser"
  timezone: "Europe/Moscow"